---
name: relaunchd-linux-ci

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure the project
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_CXX_FLAGS="-Werror" \
            --config ${{env.BUILD_TYPE}}
          cat config.h

      - name: Build the project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
